### ISSUE TITLE
Clean up old branches on remote

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/TakeTwo-WebAPI#14]
There are a few branches that have been merged back into main. Can we delete them @johnwalicki @josiemundi?

 - remotes/origin/jo-update-readme
 - remotes/origin/js-readme-update
 - remotes/origin/webapi

**Comment by josiemundi** [comment]
Yes we can delete these.

**Comment by demilolu** [comment]
reopening - not yet complete.

**Comment by upkarlidder** [comment]
Removed unused branches.
