### ISSUE TITLE
Instructions for adding APP ID /Credentials are missing in documentation README

### ISSUE THREAD

**Issue by shobhavijaystar** [Call-for-Code-for-Racial-Justice/TakeTwo-WebAPI#16]
**Describe the bug**
The README needs to provide instructions on how to setup AppID credentials for the TakeTwo 
**To Reproduce**
There is no specific steps to reproduce. README is missing the required documentation on how to fill 3 fields 
CLIENT_ID=
SECRET=
OAUTH_SERVER_URL=

**Expected behavior**
N/A

**Screenshots**
Attached is the section of the  README that needs updated documentation
Copy .env.sample file to .env file in the same directory. Fill out the CouchDB database and IBM App Id service credentials.

#CouchDB Credentials
DB_HOST=
DB_PORT=
DB_NAME=
DB_USERNAME=
DB_PASSWORD=

#IBM AppID Credentials
CLIENT_ID=
SECRET=
OAUTH_SERVER_URL=

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
 N/A

**Additional context**

**Comment by josiemundi** [comment]
Hi @shobhavijaystar thanks for this. I will add in some more information about how to get started with AppID on IBM cloud. We do want to make this part optional (#15) but it would still be good for people that want to use AppID.

**Comment by shobhavijaystar** [comment]
@josiemundi I am not sure I understood the line "it would still be good for people that want to use AppID." I tried the steps I get an error on reading of DB_PORT as "ValueError: invalid literal for int() with base 10: 'None'". I have given the port number as 5984. I suspect this is not the right place and move it to Slack channel? Are you saying we really do not need this AppID section?

**Comment by josiemundi** [comment]
@shobhavijaystar are you trying to deploy the API. You have your env file but it's not working. The part you are referring to is for couch db not AppID and should look as follows:

<img width="230" alt="CouchDBenv" src="https://user-images.githubusercontent.com/8045393/127733515-44b6594f-f85e-48be-88a7-08762605d7ac.png">

Right now you need to have AppID on IBM cloud to get the demo working. Do you have AppID credentials? If not it won't work. We are working this next sprint to remove this dependency. 

Hope this helps. Please reach out on Slack if you need any other help getting this up and running :)

**Comment by demilolu** [comment]
reopening - not yet complete.
