### ISSUE TITLE
Limit string length of highlights.

### ISSUE THREAD

**Issue by josiemundi** [Call-for-Code-for-Racial-Justice/TakeTwo-WebAPI#2]
**Is your feature request related to a problem? Please describe.**
Currently, there is no mechanism to stop someone loading a very large chunk of text into the database. 

**Describe the solution you'd like**
Set a limit on the number of characters someone can highlight. Alert the user when they exceed the length limit. 

**Describe alternatives you've considered**
Have considered letting people put in however much they like, but don't think this is desired behaviour. 

**Additional context**

**Comment by josiemundi** [comment]
@naagma5 I think @naokiabe might agree that we may not need to do this. I think we spoke about letting the user highlight as much text as they want. Not sure of your view on this @naokiabe

**Comment by naokiabe** [comment]
Yes I agree with @josiemundi that we don't need to do this @naagma5. The DS-MVP-V1 takes as input text of any length labeled as offensive or not, and learns to classify text of any length. V3, the AIX model, wants to take input text of any length and learn to predict its label and also pinpoint phrases/words in the input contributing to the label. V4, the DLL model, will take into account the sequential context of any length. So I guess we don't need to limit the highlight text length.

**Comment by naagma5** [comment]
Ok great, I will mark it as closed then. Thanks! 

@josiemundi @naokiabe
