### ISSUE TITLE
Add a unit testing

### ISSUE THREAD

**Issue by AndrewJamison** [Call-for-Code-for-Racial-Justice/TakeTwo-WebAPI#38]
**Is your feature request related to a problem? Please describe.**
There is currently no unit testing.

**Describe the solution you'd like**
We would like to add unit tests.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Holdrick** [comment]
This issue will also include a fix to the existing test since it was built before the addition of token authenticateion
