### ISSUE TITLE
Add Linter

### ISSUE THREAD

**Issue by AndrewJamison** [Call-for-Code-for-Racial-Justice/TakeTwo-WebAPI#40]
**Is your feature request related to a problem? Please describe.**
There is currently no Linter being used

**Describe the solution you'd like**
We would like to add a Linter

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by nic-jol** [comment]
### Possibilities

1. **Pylint**
- Logical (code errors and bad patterns)and statistical (formatting) linter
- Install with: `pip install pylint`
- Also a plugin with PyCharm
- Run from command line: `pylint example.py`
- e.g. output:
![Screenshot from 2022-02-17 20-39-55](https://user-images.githubusercontent.com/22651608/154613256-e1c27193-2318-44f2-9863-4ee55cf7cd47.png)

**Comment by nic-jol** [comment]
2. **Flake8**
- https://flake8.pycqa.org/en/latest/
- To Install: `python<version> -m pip install flake8`
- To use: `flake8 check.py`
- Seems to have less that it checks compared to Pylint
- E.g. output:
![Screenshot from 2022-02-17 21-42-46](https://user-images.githubusercontent.com/22651608/154618988-23df0d3d-6d63-40d0-b8cc-492d318acc06.png)

**Comment by nic-jol** [comment]
3. **Pylama**
- https://github.com/klen/pylama
- To Install: `pip install pylama`
- Can recursively run on current directory with `pylama`
- Output similar to Pylint
- E.g. output
![Screenshot from 2022-02-17 21-51-36](https://user-images.githubusercontent.com/22651608/154619742-fe61b9b5-2c34-40fc-b673-3172b446a2f2.png)

**Comment by nic-jol** [comment]
4. Super-Linter
- https://github.com/github/super-linter
- Runs all of these linters automatically for Python3: 
- Easy to create a GitHub workflow action for by following the guide on GitHub
- Might be a bit heavy for a project that is only involves Python
- Can also run locally: https://github.com/github/super-linter/blob/main/docs/run-linter-locally.md
`sudo docker run -e RUN_LOCAL=true -e DEFAULT_WORKSPACE=~/cfcfrj/taketwo-webapi -v /home/username/cfcfrj/taketwo-webapi:/home/username/cfcfrj/taketwo-webapi/taketwo-webapi github/super-linter`
- E.g. output
![Screenshot from 2022-02-22 15-28-52](https://user-images.githubusercontent.com/22651608/155230386-7f95ad55-73c4-4389-adde-b16bb5614196.png)

**Comment by nic-jol** [comment]
> ### Possibilities
> 
>     1. **Pylint**
> 
> 
>     * Logical (code errors and bad patterns)and statistical (formatting) linter
> 
>     * Install with: `pip install pylint`
> 
>     * Also a plugin with PyCharm
> 
>     * Run from command line: `pylint example.py`
> 
>     * e.g. output:
>       ![Screenshot from 2022-02-17 20-39-55](https://user-images.githubusercontent.com/22651608/154613256-e1c27193-2318-44f2-9863-4ee55cf7cd47.png)

This can also be easily added as a Github Action/Workflow for pull requests using the following Marketplace action: https://github.com/marketplace/actions/pylint-action

**Comment by upkarlidder** [comment]
Thank you for the detail comparison @nic-jol. Can you please also look at [Black](https://github.com/psf/black) and post your results here. We can pick between flake8 and black.

**Comment by upkarlidder** [comment]
Superlinter was added after discussing with the team.
