### ISSUE TITLE
Add github action to automate Linting

### ISSUE THREAD

**Issue by AndrewJamison** [Call-for-Code-for-Racial-Justice/TakeTwo-WebAPI#41]
**Is your feature request related to a problem? Please describe.**
There is currently no automatic Linting 

**Describe the solution you'd like**
We would like to add a github action to automate Linting

**Describe alternatives you've considered**
N/A

**Additional context**
Linting will be added in this issue: https://github.com/Call-for-Code-for-Racial-Justice/TakeTwo-Marker-ChromeExtension/actions/runs/1819830294

**Comment by nic-jol** [comment]
Attempting to add this action: https://github.com/marketplace/actions/python-linter
